[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle 404 errors properly for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404