[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cache configuration
[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
      paths = [
        ".next/cache",          # Next.js cache
        "node_modules/.cache"   # Node modules cache
      ]

# Ensure blog files are available
[[redirects]]
  from = "/blog/*"
  to = "/.next/server/pages/blog/:splat"
  status = 200

# Ensure content/blog is copied to the build
[[edge_functions]]
  function = "content"
  path = "/content/*"

[[redirects]]
  from = "/content/*"
  to = "/.next/server/pages/content/:splat"
  status = 200