[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cache configuration
[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
      paths = [
        ".next/cache",          # Next.js cache
        "node_modules/.cache"   # Node modules cache
      ]

# Handle static files
[[redirects]]
  from = "/blog/*"
  to = "/.next/static/blog/:splat"
  status = 200
  force = true

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.next/server/app/api/:splat"
  status = 200
  force = true

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404